#!/bin/bash

trials=4

./orchestration/run    sunsh $trials ../discern_data/data/malicious/spread          spread
./orchestration/run    sunsh $trials ../discern_data/data/malicious/exfiltrate          upload
# ./orchestration/run    sunsh $trials ../discern_data/data/malicious/packetsniffer   packetsniffer
./orchestration/run -f sunsh $trials ../discern_data/data/malicious/cryptominer          crypto
./orchestration/run -f sunsh $trials ../discern_data/data/malicious/ransomware      ransomware
./orchestration/run    sunsh $trials ../discern_data/data/malicious/portscanner     portscanner
./orchestration/run    sunsh $trials ../discern_data/data/malicious/internetscanner internetscanner


./orchestration/run    sunsh $trials ../discern_data/data/legitimate/dnsmitm        dnsmitm
./orchestration/run -f sunsh $trials ../discern_data/data/legitimate/imgnet         svm
./orchestration/run    sunsh $trials ../discern_data/data/legitimate/synflood       synflood
./orchestration/run -f sunsh $trials ../discern_data/data/legitimate/gpt            llm

cd ../discern_data && git add * && git commit -m "re-running all the data" && git push

