#!/bin/bash

trials=4

./orchestration/run    sunsh $trials ../official/data/malicious/internetscanner internetscanner
(cd ../official && git add * && git commit -m "re-running all the data" && git push)
./orchestration/run -f sunsh $trials ../official/data/malicious/ransomware      ransomware
(cd ../official && git add * && git commit -m "re-running all the data" && git push)
./orchestration/run    sunsh $trials ../official/data/legitimate/dnsmitm        dnsmitm
./orchestration/run -f sunsh $trials ../official/data/legitimate/gpt            gpt
./orchestration/run -f sunsh $trials ../official/data/legitimate/imgnet         imgnet
./orchestration/run    sunsh $trials ../official/data/legitimate/synflood       synflood
./orchestration/run    sunsh $trials ../official/data/malicious/spread          spread
./orchestration/run    sunsh $trials ../official/data/malicious/upload          upload
./orchestration/run    sunsh $trials ../official/data/malicious/packetsniffer   packetsniffer
./orchestration/run    sunsh $trials ../official/data/malicious/portscanner     portscanner

cd ../official && git add * && git commit -m "re-running all the data" && git push

